spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/springsecurity?userSSL=false
    username: root
#  security:
#    user:
#      name: harsh
#      password: pass