spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:/Users/harshvaghani/Desktop/programmingprojects/javaspringboot/springboot-4/homework/week2/homework-week2/db
    username: harsh
    password: harsh
  jpa:
    hibernate:
      ddl-auto: create